name: Format

on:
  push:
    branches:
      - main

jobs:
  format:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run code formatter
        run: npm run format

      - name: Commit and push formatted changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Auto-format files'
          branch: main


